#! /bin/bash

set -xe

dir=$(pwd)

ln -sfn $dir/vim $HOME/.vim
ln -sf $dir/vim/vimrc $HOME/.vimrc

ln -sfn $dir/mail $HOME/.mail

ln -sf $dir/bashrc $HOME/.bashrc.local
ln -sf $dir/aliases/forall $HOME/.aliases.forall
ln -sf $dir/git/config $HOME/.gitconfig

# Setup platform dependent links.
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    mkdir -p $XDG_CONFIG_HOME/fontconfig $HOME/.config/i3

    ln -sf $dir/aliases/linux-gnu $HOME/.aliases
    ln -sf $dir/x/xinitrc $HOME/.xinitrc
    ln -sf $dir/x/Xresources $HOME/.Xresources
    ln -sf $dir/i3/i3 $HOME/.config/i3/config
    ln -sf $dir/screen/fonts.conf $XDG_CONFIG_HOME/fontconfig/fonts.conf

    localectl --no-convert  \
        set-x11-keymap us,ru pc105 "" grp:switch,grp:caps_toggle,grp_led:caps
elif [[ "$OSTYPE" == "cygwin" ]]; then
    ln -sf $dir/aliases/win $HOME/.aliases

    sh $dir/git/forall.sh
    sh $dir/git/forwin.sh
elif [[ "$OSTYPE" == "darwin"* ]]; then
    ln -sf $dir/aliases/darwin $HOME/.aliases
else
    echo "Not implemented: ${OSTYPE}"
    exit 1
fi
