#! /bin/bash

set -xe

dir=$(pwd)

# Setup for vim
ln -s -f $dir/.vim $HOME/.vim
ln -s -f $dir/.vimrc $HOME/.vimrc

ln -s -f $dir/.gitconfig $HOME/.gitconfig

ln -s -f $dir/.aliases $HOME/.aliases

ln -s -f $dir/.xinitrc $HOME/.xinitrc
ln -s -f $dir/.Xresources $HOME/.Xresources

ln -s -f $dir/.i3 $HOME/.config/i3/config
ln -s -f $dir/.mutt/muttrc $HOME/.muttrc

xrdb -merge $HOME/.Xresources

