" Plugins {{{

call plug#begin('~/.vim/plugged') " Directory for plugins

" Dependencies:
Plug 'tpope/vim-rhubarb'

" Languages:
Plug 'fatih/vim-go', {'for': 'go'}

" General:
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/vim-easy-align'
Plug 'vimwiki/vimwiki'
Plug 'MattesGroeger/vim-bookmarks'
Plug 'lyuts/vim-rtags'
Plug 'junegunn/gv.vim'
Plug 'mileszs/ack.vim'

Plug 'aklt/plantuml-syntax'
Plug 'scrooloose/vim-slumlord'

Plug 'altercation/vim-colors-solarized'
Plug 'junegunn/seoul256.vim'

call plug#end()
" }}}

" Plugins Settings {{{

" Plugin: 'vimwiki/vimwiki'
let g:vimwiki_list = [{'path': '~/doc', 'index': 'main'},
            \ {'path': '$HOME/dev', 'syntax': 'markdown', 'ext': '.md'}]


" Language: Go
" Tagbar configuration for Golang
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }
" }}}

" General settings {{{

fun! InstallGeneralSettings()
    set modelines=1

    let g:mapleader = ","

    " Disable the CtrlP mapping, since we want to use FZF instead for <c-p>.
    let g:ctrlp_map = ''

    " Default indentation.
    " ts - tabstop
    " sts - softtabstop (insert mode)
    " sw - shiftwidth (normal mode)
    set ts=4 sts=4 sw=4 expandtab

    set colorcolumn=80
    set clipboard=unnamedplus


    " Mapping for coping to a clipboard.
    vnoremap <C-c> "+y

    call SetCodeModeColor()

    set number
    set laststatus=2

    set hidden
    set backspace=2
    set ruler

    " Don't show an error during the work with buffers.
    set noerrorbells
    set novisualbell

    " Search
    set incsearch               " move to match as you type the search query
    set hlsearch                " enable search result highlighting
    set ignorecase
    set smartcase

    set wildmode=list:longest,full

    set lazyredraw

    filetype plugin indent on

    if has("autocmd")
        augroup vimrc
            autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
            autocmd FileType ruby,yml setlocal ts=2 sts=2 sw=2 expandtab nocursorline
            autocmd FileType go setlocal ts=4 sts=4 sw=4 noexpandtab
            autocmd FileType asm set ft=nasm

            call SetPythonLocalSettings()
            call SetCLocalSettings()
            call SetGoLocalSettings()
            call SetRubyLocalSettings()

            autocmd BufWritePre * call StripTrailingWhiteSpaces()
            autocmd BufWritePre *.rb,*.c,*.cpp,*.h,*.wiki call SquashBlankLines()
            autocmd FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>
        augroup END
    endif

    if has('mouse')
        set mouse=a
    endif
    set mousehide

    set splitbelow
    set splitright

    set updatetime=1000
    set history=1000
    set undolevels=1000

    set title
endfun
" }}}

" Mappings {{{

fun! SetMappings()
    noremap <Up> <Nop>
    noremap <Down> <Nop>
    noremap <Left> <Nop>
    noremap <Right> <Nop>

    " Makes the switching between buffers easy.
    noremap <C-h> <C-w>h
    noremap <C-j> <C-w>j
    noremap <C-k> <C-w>k
    noremap <C-l> <C-w>l

    nnoremap <leader>k :vsplit<CR>
    nnoremap <leader>h :split<CR>
    nnoremap <leader>q :close<CR>

    " Center the screen quickly
    nnoremap <space> zz

    nnoremap <leader>m :nohlsearch<CR>

    " These mappings will make it so that going to the next one in a search will
    " center on the line it's found in.
    nnoremap n nzzzv
    nnoremap N Nzzzv

    noremap j gj
    noremap k gk

    " Find merge conflict markers
    nnoremap <leader>lc /\v^[<\|=>]{7}( .*\|$)<CR>

    nnoremap <silent> <leader>d "_d
    vnoremap <silent> <leader>d "_d

    inoremap jj <Esc>

    nnoremap <C-p> :FZF<CR>
    nnoremap <C-b> :Buffers<CR>
    nnoremap <leader>go :Goyo<CR>

    nnoremap<leader>vm :tabedit $MYVIMRC<CR>
    nnoremap<leader>vr :vertical resize 127<CR>

    nnoremap<leader>tb :TagbarToggle<CR>

    " Open/close folding
    nnoremap<leader><space> za<CR>

    nnoremap<leader>a :Ack <cword><CR>
    nnoremap<leader>gr :Ggrep <cword><CR>

    nnoremap<leader>cm :call SetCodeModeColor()<CR>
    nnoremap<leader>wm :call SetWriteModeColor()<CR>

    nnoremap<leader>sv :source $MYVIMRC<CR>
endfun

" }}}

" Python settings {{{
fun! SetPythonLocalSettings()
    augroup python
        autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab
        autocmd FileType python setlocal colorcolumn=80
    augroup END
endfun
" }}}

" C settings {{{
fun! SetCLocalSettings()
    augroup c
        autocmd FileType c setlocal ts=4 sts=4 sw=4 noexpandtab
        autocmd FileType c setlocal colorcolumn=80
    augroup END
endfun
" }}}

" Go settings {{{
fun! SetGoLocalSettings()
    augroup go
        autocmd FileType go setlocal colorcolumn=80

        let g:go_disable_autoinstall = 0
        let g:go_highlight_types = 1
        let g:go_highlight_extra_types = 1
        let g:go_highlight_functions = 1
        let g:go_highlight_methods = 1
        let g:go_highlight_structs = 1
        let g:go_highlight_fields = 1
        let g:go_highlight_operators = 1
        let g:go_highlight_build_constraints = 1
        let g:go_fmt_command = "goimports"

        autocmd FileType go noremap <leader>b <Plug>(go-build)
        autocmd FileType go noremap <Leader>ds <Plug>(go-def-split)
        autocmd FileType go noremap <Leader>dv <Plug>(go-def-vertical)
        autocmd FileType go noremap <Leader>gv <Plug>(go-doc-vertical)
        autocmd FileType go noremap <Leader>s <Plug>(go-implements)
        autocmd FileType go noremap <Leader>gb :GoDocBrowser<CR>
        autocmd FileType go noremap <Leader>gd :GoDoc<CR>
        autocmd FileType go noremap <leader>t :GoTest<CR>
        autocmd FileType go noremap <Leader>e :GoRename<CR>
        autocmd FileType go noremap <leader>c :GoCoverageBrowser<CR>
        autocmd FileType go noremap <leader>r :GoReferrers<CR>
        autocmd FileType go noremap <leader>l :GoLint<CR>
    augroup END
endfun
" }}}

" Ruby settings {{{

fun! SetRubyLocalSettings()
    augroup ruby
        autocmd FileType ruby setlocal colorcolumn=80
    augroup END
endfun

" }}}

" Color scheme modes {{{

fun! SetCodeModeColor()
    let g:seoul256_background = 233
    colorscheme seoul256
    highlight colorcolumn ctermbg=236
endfun

fun! SetWriteModeColor()
    set nonumber
    let g:solarized_termcolors=256
    colorscheme solarized
    set background=light
endfun

" }}}

" Helpers {{{

" Executes an input command and saves the current state.
fun! ExecAndSave(cmd)
    " Save the last search.
    let _s=@/

    " Save the cursor position.
    let pos=getpos(".")

    " Exec a command.
    execute a:cmd

    " Restore the search and the cursor position.
    let @/=_s
    call setpos(".", pos)
endfun

fun! StripTrailingWhiteSpaces()
    call ExecAndSave("%s/\\s\\+$//e")
endfun

fun! SquashBlankLines()
    call ExecAndSave(":g/^\\_$\\n\\_^$/d")
endfun

fun! SetupMisspellings()
    nnoremap <silent><leader>f :set spell!<CR>
    set spelllang=en_us
endfun

fun! SetBackup()
    set backup
    set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
    set backupskip=/tmp/*,/private/tmp/*
    set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
    set writebackup
endfun

" }}}

" Settings installation {{{

call InstallGeneralSettings()
call SetMappings()
call SetupMisspellings()
call SetBackup()

" }}}

" vim:foldmethod=marker:foldlevel=0
