source ~/.vim/plugins
source ~/.vim/mappings
source ~/.vim/backup
source ~/.vim/helpers
source ~/.vim/statusline
source ~/.vim/colors

if has("autocmd")
    source ~/.vim/autocmd
endif

" General settings {{{

set modelines=1
set clipboard=unnamedplus

set colorcolumn=80
set laststatus=2
set backspace=2
set hidden
set number
set ruler
set title

set noerrorbells  " Don't show an error during the work with buffers.
set novisualbell

set incsearch     " move to match as you type the search query
set hlsearch      " enable search result highlighting
set ignorecase
set smartcase

set wildmode=list:longest,full
set lazyredraw

filetype plugin indent on

if has('mouse')
    set mouse=a
endif
set mousehide

set splitbelow
set splitright

set updatetime=1000
set history=1000
set undolevels=1000

set spelllang+=en_us
set spelllang+=ru

set exrc
set secure

" }}}

call SetupSpaces()

" vim:foldmethod=marker:foldlevel=0
