#!/bin/bash

set -xe

usrdir=~/.config/systemd/user
mkdir -p $usrdir

services=(
    rdm.service
)

sockets=(rdm.socket)

known_units=("${services[@]}" "${sockets[@]}")
units_to_enable=("${sockets[@]}")
units_to_start=("${sockets[@]}" rdm.service)

for unit in "${known_units[@]}"
do
    if [ -f "$usrdir/$unit" ]; then
        systemctl --user stop $unit
        systemctl --user disable $unit
    fi

    ln -s -f $(pwd)/systemd/$unit $usrdir/$unit
done

systemctl --user daemon-reload

for unit in "${units_to_enable[@]}"
do
    systemctl --user enable $unit
done

for unit in "${units_to_start[@]}"
do
    systemctl --user start $unit
done
