setxkbmap -option
setxkbmap -option 'grp:switch,grp:caps_toggle,grp_led:caps'
setxkbmap -model 'pc105' -layout us,ru

xrdb -merge ~/.Xresources

start-pulseaudio-x11

. /etc/X11/xinit/xinitrc-common

exec i3
