#!/bin/bash
#
# Downloads and installs the specified LLVM version.
#
# Requirements:
#  * Tool chain: svn, cmake, make, gcc, g++.
#  * Platform:
#     * Linux
#     * Windows (cygwin)
#
# References:
#  * http://clang.llvm.org/get_started.html
#  * https://compiler-rt.llvm.org/
SUDO=sudo
if [[ "$OSTYPE" == "cygwin" ]]; then
    SUDO=
fi

function download()
{
    local release=$1
    local download_path=$2

    svn co http://llvm.org/svn/llvm-project/llvm/tags/$release/final $download_path

    pushd $download_path
        pushd tools
            svn co http://llvm.org/svn/llvm-project/cfe/tags/$release/final clang
            pushd clang/tools
                svn co https://llvm.org/svn/llvm-project/clang-tools-extra/tags/$release/final extra
            popd # clang/tools
        popd # tools

        pushd projects
            svn co http://llvm.org/svn/llvm-project/compiler-rt/tags/$release/final compiler-rt
        popd # projects
    popd # $download_path
}

function install()
{
    local release=$1
    local src_path=$2
    local build_path=$3
    local parallelism=$4
    local make_flags="-j$parallelism --load-average $parallelism"

    pushd $build_path
        cmake -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=/usr/bin/gcc \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
            -DCMAKE_ASM_COMPILER=/usr/bin/gcc \
            $src_path
        make $make_flags
        $SUDO make $make_flags install
    popd # $build_path
}

help="LLVM downloader and installer

Usage: llvm [OPTIONS]

Options:

-r, --release - LLVM release id in format: RELEASE_600 (LLVM 6.0.0)
-s, --download-path - path where to download LLVM sources
-b, --build-path - path where store the compilation result
-p, --parallelism - value for make -j option
-h, --help - print this message"

while [[ "$#" > 0 ]]; do case $1 in
  -r|--release) release="$2"; shift;;
  -d|--download-path) download_dir=$2; shift;;
  -b|--build-path) build_dir=$2; shift;;
  -p|--parallelism) parallelism=$2 shift;;
  -h|--help) echo "$help"; exit 0;;
  *) echo "unknown parameter passed: $1"; exit 1;;
esac; shift; done

set -xe

if [ -z "$release" ]; then
    release=RELEASE_700
fi

if [ -z "$download_dir" ]; then
    download_dir=$HOME/src
fi

if [ -z "$build_dir" ]; then
    build_dir=$HOME/build
fi
if [ -z "$parallelism" ]; then
    parallelism=$(nproc)
fi

build_path=$build_dir/llvm_$release
download_path=$download_dir/llvm_$release

mkdir -p $download_path $build_path

download  "$release" "$download_path"
install "$release" "$download_path" "$build_path" "$parallelism"
