#! /bin/bash

set -e

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | \
    ctags --c++-kinds=+p \
          --fields=+iaS \
          --extra=+q \
          --language-force=C++ \
          --append=yes \
          --recurse=yes \
          --sort=yes \
          --tag-relative -L - -f"$dir/$$.tags"

mv "$dir/$$.tags" "$dir/tags"

# vim:syntax=sh
